service: github-wechat-webhook
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hook:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
