service: github-webchat-webhook
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hook:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
